package pl.edu.us.medrala.szymon.aiagent.cards;

public enum Ability {
    NONE, COMMANDERS_HORN, DECOY, HERO, MEDIC, MORALE_BOOST, MUSTER, SCORCH, SPY, TIGHT_BOND;

    public enum Leader {
        THE_STEEL_FORGED, THE_SIEGEMASTER, LORD_COMMANDER_OF_THE_NORTH, KING_OF_TEMERIA,
        THE_RELENTLESS, THE_WHITE_FLAME, THE_EMPEROR_OF_NILFGAARD, HIS_IMPERIAL_MAJESTY,
        QUEEN_OF_DOL_BLATHANNA, THE_BEAUTIFUL, DAISY_OF_THE_VALLEY, PUREBLOOD_ELF,
        DESTROYER_OF_WORLDS, BRINGER_OF_DEATH, KING_OF_THE_WILD_HUNT, COMMANDER_OF_THE_RED_RIDERS
    }
}
