server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:aiAgent
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#    show-sql: true
